import assert from 'node:assert/strict';
import test from 'node:test';
import { chmod, lstat, mkdtemp, readFile, symlink, unlink, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { CorrelationSafetyError, CorrelationStore, createIntent, requestFingerprint } from '../src/correlation-store.js';
import { langGraphApprovalKey, langGraphOperationKey, openLangGraphSqlite, pauseLangGraph, resumeLangGraph, safeLangGraphWorkflow, validateLangGraphSqlite } from '../src/langgraph.js';
import type { OaeTask } from '../src/openagentemail.js';
import { sanitizedTimeline } from '../src/sanitize.js';

const runner = join(process.cwd(), 'node_modules/tsx/dist/cli.mjs'); const fixture = join(process.cwd(), 'test/fixtures/langgraph-r3-child.ts'); const threadId = 'r3-thread-000000000001'; const correlationId = '77777777-7777-4777-8777-777777777777';
type Identity = { threadId: string; correlationId: string };
const primary: Identity = { threadId, correlationId };
const donor: Identity = { threadId: 'r3-thread-000000000002', correlationId: '99999999-9999-4999-8999-999999999999' };
function child(mode: 'pause' | 'decide' | 'resume', directory: string, decision: 'approved' | 'rejected', identity: Identity = primary): void { const result = spawnSync(process.execPath, [runner, fixture, mode, directory, decision, identity.threadId, identity.correlationId], { encoding: 'utf8', env: {} }); assert.equal(result.status, 0, `${mode}: ${result.stderr}`); }
async function pausedDirectory(decision: 'approved' | 'rejected', terminal = true, identity: Identity = primary): Promise<string> { const directory = await mkdtemp(join(tmpdir(), `r3-${decision}-`)); child('pause', directory, decision, identity); if (terminal) child('decide', directory, decision, identity); return directory; }
async function durable(directory: string, identity: Identity = primary) { const store = new CorrelationStore(join(directory, 'correlation')); return { store, record: await store.load(identity.correlationId), task: JSON.parse(await readFile(join(directory, 'oae-task.json'), 'utf8')) as OaeTask }; }
async function optionalText(path: string): Promise<string | null> { try { return await readFile(path, 'utf8'); } catch { return null; } }
function effectPaths(directory: string, identity: Identity = primary) { return { ledger: join(directory, `langgraph-effect-ledger-${identity.correlationId}.json`), observation: join(directory, `langgraph-effect-observation-${identity.correlationId}.json`) }; }

test('R3 real SQLite-backed interrupt fresh-process restores approved and rejected with exact second resume no-op', async () => {
  for (const decision of ['approved', 'rejected'] as const) {
    const directory = await pausedDirectory(decision); child('resume', directory, decision); const first = JSON.parse(await readFile(join(directory, 'result.json'), 'utf8')) as Record<string, unknown>; const ledgerPath = join(directory, `langgraph-effect-ledger-${correlationId}.json`); const observationPath = join(directory, `langgraph-effect-observation-${correlationId}.json`); const ledgerAfterFirst = await readFile(ledgerPath, 'utf8'); const observationAfterFirst = await readFile(observationPath, 'utf8'); child('resume', directory, decision);
    const paused = JSON.parse(await readFile(join(directory, 'pause-result.json'), 'utf8')) as Record<string, unknown>; const result = JSON.parse(await readFile(join(directory, 'result.json'), 'utf8')) as Record<string, unknown>;
    assert.deepEqual(paused, { phase: 'awaiting-input', taskId: 'r3-task-1', threadId, operationKey: langGraphOperationKey(threadId), inputEvents: 1 }); for (const output of [first, result]) { assert.equal(output.phase, 'resumed'); assert.equal(output.taskId, 'r3-task-1'); assert.equal(output.threadId, threadId); assert.equal(output.operationKey, langGraphOperationKey(threadId)); assert.equal(output.decision, decision); assert.equal(output.effects, 1); assert.equal(output.inputEvents, 1); assert.match(String(output.checkpointId), /^[A-Za-z0-9-]{16,120}$/); assert.match(String(output.finalStateFingerprint), /^[0-9a-f]{64}$/); assert.match(String(output.effectObservationFingerprint), /^[0-9a-f]{64}$/); } assert.equal(await readFile(ledgerPath, 'utf8'), ledgerAfterFirst); assert.equal(await readFile(observationPath, 'utf8'), observationAfterFirst);
    const database = join(directory, 'langgraph-checkpoints.sqlite'); assert.equal((await lstat(database)).mode & 0o777, 0o600); await validateLangGraphSqlite(directory);
  }
});

test('R3 resume-started missing receipt fails closed before a real Command or replayed node effect', async () => {
  const directory = await pausedDirectory('approved'); const initial = await durable(directory); await assert.rejects(() => resumeLangGraph({ directory, threadId, record: initial.record, correlationStore: initial.store, task: initial.task, checkpoints: async (name) => { if (name === 'after-resume-started') throw new Error('crash-after-started'); } }), /crash-after-started/); const started = await initial.store.load(correlationId); assert.equal(started.phase, 'resume-started'); let effects = 0;
  await assert.rejects(() => resumeLangGraph({ directory, threadId, record: started, correlationStore: initial.store, task: initial.task, onEffect: () => { effects += 1; } }), CorrelationSafetyError); assert.equal((await initial.store.load(correlationId)).phase, 'resume-started'); assert.equal(effects, 0);
});

test('R3 L5 durable resume matrix covers protected effect, observation, completion, receipt and resumed windows', async () => {
  const rows: Array<{ checkpoint: string; recovery: 'run' | 'receipt' | 'closed'; ledger: boolean; observation: boolean }> = [
    { checkpoint: 'before-resume-started', recovery: 'run', ledger: false, observation: false }, { checkpoint: 'after-resume-started', recovery: 'closed', ledger: false, observation: false }, { checkpoint: 'before-command-resume', recovery: 'closed', ledger: false, observation: false }, { checkpoint: 'before-graph-completion', recovery: 'closed', ledger: false, observation: false }, { checkpoint: 'before-protected-effect', recovery: 'closed', ledger: false, observation: false }, { checkpoint: 'after-protected-effect-before-observation', recovery: 'closed', ledger: true, observation: false }, { checkpoint: 'before-effect-observation', recovery: 'closed', ledger: true, observation: false }, { checkpoint: 'after-effect-observation', recovery: 'closed', ledger: true, observation: true }, { checkpoint: 'after-command-resume', recovery: 'closed', ledger: true, observation: true }, { checkpoint: 'after-graph-completion', recovery: 'closed', ledger: true, observation: true }, { checkpoint: 'before-receipt-save', recovery: 'closed', ledger: true, observation: true }, { checkpoint: 'after-receipt-save', recovery: 'receipt', ledger: true, observation: true }, { checkpoint: 'before-resumed-save', recovery: 'receipt', ledger: true, observation: true }, { checkpoint: 'after-resumed-save', recovery: 'receipt', ledger: true, observation: true },
  ];
  for (const row of rows) {
    const directory = await pausedDirectory('approved'); const current = await durable(directory); const hits: string[] = []; await assert.rejects(() => resumeLangGraph({ directory, threadId, record: current.record, correlationStore: current.store, task: current.task, checkpoints: async (name) => { hits.push(name); if (name === row.checkpoint) throw new Error(`crash-${name}`); } }), new RegExp(`crash-${row.checkpoint}`)); assert.ok(hits.includes(row.checkpoint), `unreached ${row.checkpoint}`); const paths = effectPaths(directory); const ledger = await optionalText(paths.ledger); const observation = await optionalText(paths.observation); assert.equal(ledger !== null, row.ledger, row.checkpoint); assert.equal(observation !== null, row.observation, row.checkpoint); const after = await current.store.load(correlationId);
    if (row.recovery === 'closed') { await assert.rejects(() => resumeLangGraph({ directory, threadId, record: after, correlationStore: current.store, task: current.task }), CorrelationSafetyError); assert.equal((await current.store.load(correlationId)).phase, 'resume-started'); assert.equal(await optionalText(paths.ledger), ledger); assert.equal(await optionalText(paths.observation), observation); }
    else { const recovered = await resumeLangGraph({ directory, threadId, record: after, correlationStore: current.store, task: current.task }); assert.equal(recovered.phase, 'resumed'); if (row.recovery === 'run') { assert.ok(await optionalText(paths.ledger)); assert.ok(await optionalText(paths.observation)); } else { assert.equal(await optionalText(paths.ledger), ledger); assert.equal(await optionalText(paths.observation), observation); } }
  }
});

test('R3 L5 decision-evidence before-after windows recover exactly before any protected effect', async () => {
  for (const checkpoint of ['before-decision-evidence', 'after-decision-evidence']) { const directory = await pausedDirectory('approved'); const current = await durable(directory); const hits: string[] = []; await assert.rejects(() => resumeLangGraph({ directory, threadId, record: current.record, correlationStore: current.store, task: current.task, checkpoints: async (name) => { hits.push(name); if (name === checkpoint) throw new Error(`crash-${name}`); } }), new RegExp(`crash-${checkpoint}`)); assert.ok(hits.includes(checkpoint), `unreached ${checkpoint}`); const after = await current.store.load(correlationId); assert.equal(after.phase, checkpoint === 'before-decision-evidence' ? 'awaiting-input' : 'decision-received'); assert.equal(await optionalText(effectPaths(directory).ledger), null); const resumed = await resumeLangGraph({ directory, threadId, record: after, correlationStore: current.store, task: current.task }); assert.equal(resumed.phase, 'resumed'); assert.ok(await optionalText(effectPaths(directory).ledger)); assert.ok(await optionalText(effectPaths(directory).observation)); }
});

test('R3 L5 initial invoke/checkpoint visibility and R1 create/input before-after windows recover without duplicate OAE effects', async () => {
  for (const crashAt of ['before-initial-invoke', 'after-initial-invoke', 'before-checkpoint-visible', 'after-checkpoint-visible', 'before-task-adopt', 'after-task-adopt', 'before-input-accept', 'after-input-accept']) {
    const directory = await mkdtemp(join(tmpdir(), `r3-pause-${crashAt}-`)); const id = '88888888-8888-4888-8888-888888888888'; const store = new CorrelationStore(join(directory, 'correlation')); const canonical = { requester: 'requester@example.test', responder: 'responder@example.test', subject: 'R3 LangGraph approval', body: 'raw-workflow-r3' }; const record = createIntent({ framework: 'langgraph', correlationId: id, operationKey: langGraphOperationKey(threadId), requestFingerprint: requestFingerprint(canonical), expectedParticipants: { requester: canonical.requester, responder: canonical.responder }, frameworkStateRef: 'langgraph-checkpoints.sqlite', approvalItemKey: langGraphApprovalKey(threadId), now: '2026-02-03T00:00:00.000Z' }); await store.save(record); let task: OaeTask | undefined; let creates = 0; let inputs = 0;
    const oae = { create: async (request: { to: string; subject: string; body: string }) => { creates += 1; task = { id: 'r3-crash-task', from: canonical.requester, to: request.to, subject: request.subject, state: 'submitted', createdAt: '2026-02-03T00:00:00.000Z', updatedAt: '2026-02-03T00:00:00.000Z', messages: [{ id: 'root', from: canonical.requester, to: request.to, subject: request.subject, date: '2026-02-03T00:00:00.000Z', state: 'submitted', body: request.body }] }; return task; }, list: async () => task ? [task] : [], get: async () => { if (!task) throw new Error('missing task'); return task; }, inputRequired: async (_id: string, body: string) => { if (!task) throw new Error('missing task'); inputs += 1; task = { ...task, state: 'input-required', updatedAt: '2026-02-03T00:00:01.000Z', messages: [...task.messages, { id: 'input', from: canonical.requester, to: canonical.responder, subject: task.subject, date: '2026-02-03T00:00:01.000Z', state: 'input-required', body }] }; return task; } };
    const hits: string[] = []; await assert.rejects(() => pauseLangGraph({ directory, threadId, workflow: canonical.body, record, correlationStore: store, oae, checkpoints: async (name) => { hits.push(name); if (name === crashAt) throw new Error(`crash-${name}`); } }), new RegExp(`crash-${crashAt}`)); assert.ok(hits.includes(crashAt), `unreached ${crashAt}`); const recovered = await pauseLangGraph({ directory, threadId, workflow: canonical.body, record: await store.load(id), correlationStore: store, oae }); assert.equal(recovered.phase, 'awaiting-input'); assert.equal(creates, 1, crashAt); assert.equal(inputs, 1, crashAt);
  }
});

test('R3b real completed ledger, observation and v2 receipt reject cross-correlation/thread/decision replay and every bound field mutation', async () => {
  const directory = await pausedDirectory('approved'); child('resume', directory, 'approved'); const current = await durable(directory);
  const donorDirectory = await pausedDirectory('rejected', true, donor); child('resume', donorDirectory, 'rejected', donor);
  const paths = { ledger: effectPaths(directory).ledger, observation: effectPaths(directory).observation, receipt: join(directory, 'langgraph-receipt.json') } as const;
  const originals = { ledger: await readFile(paths.ledger, 'utf8'), observation: await readFile(paths.observation, 'utf8'), receipt: await readFile(paths.receipt, 'utf8') };
  const donorArtifacts = { ledger: await readFile(effectPaths(donorDirectory, donor).ledger, 'utf8'), observation: await readFile(effectPaths(donorDirectory, donor).observation, 'utf8'), receipt: await readFile(join(donorDirectory, 'langgraph-receipt.json'), 'utf8') };
  const recordBytes = JSON.stringify(current.record); const taskBytes = await readFile(join(directory, 'oae-task.json'), 'utf8');
  const reject = async (artifact: keyof typeof paths, mutated: string, label: string) => {
    await writeFile(paths[artifact], mutated, { mode: 0o600 }); const before = { ...originals, [artifact]: mutated }; let effects = 0;
    await assert.rejects(() => resumeLangGraph({ directory, threadId, record: current.record, correlationStore: current.store, task: current.task, onEffect: () => { effects += 1; } }), CorrelationSafetyError, label);
    assert.equal(effects, 0, label); assert.equal(JSON.stringify((await current.store.load(correlationId))), recordBytes, label); assert.equal(await readFile(join(directory, 'oae-task.json'), 'utf8'), taskBytes, label); for (const name of Object.keys(paths) as Array<keyof typeof paths>) assert.equal(await readFile(paths[name], 'utf8'), before[name], label);
    await writeFile(paths[artifact], originals[artifact], { mode: 0o600 });
  };
  for (const artifact of Object.keys(paths) as Array<keyof typeof paths>) await reject(artifact, donorArtifacts[artifact], `real cross-correlation/thread/decision ${artifact} replay`);
  const change: Record<string, unknown> = { correlationId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', taskId: 'other-task', requestFingerprint: 'a'.repeat(64), operationKey: 'langgraph/oae-approval-graph/await_authoritative_decision/other-thread', threadId: 'other-thread', decision: 'rejected', messageId: 'other-message', evidenceFingerprint: 'b'.repeat(64), version: 9, effectId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', effectLedgerFingerprint: 'c'.repeat(64), effectObservationFingerprint: 'd'.repeat(64), finalCheckpointId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', finalStateFingerprint: 'e'.repeat(64), effects: 0 };
  const fields: Record<keyof typeof paths, string[]> = { ledger: ['correlationId', 'taskId', 'requestFingerprint', 'operationKey', 'threadId', 'decision', 'messageId', 'evidenceFingerprint', 'version', 'effectId'], observation: ['correlationId', 'taskId', 'requestFingerprint', 'operationKey', 'threadId', 'decision', 'messageId', 'evidenceFingerprint', 'version', 'effectLedgerFingerprint', 'effects'], receipt: ['correlationId', 'taskId', 'requestFingerprint', 'operationKey', 'threadId', 'decision', 'messageId', 'evidenceFingerprint', 'version', 'finalCheckpointId', 'finalStateFingerprint', 'effectObservationFingerprint', 'effects'] };
  for (const artifact of Object.keys(paths) as Array<keyof typeof paths>) {
    for (const field of fields[artifact]) { const row = JSON.parse(originals[artifact]) as Record<string, unknown>; row[field] = change[field]; await reject(artifact, JSON.stringify(row), `${artifact}.${field}`); }
    for (const shape of ['missing', 'extra'] as const) { const row = JSON.parse(originals[artifact]) as Record<string, unknown>; if (shape === 'missing') delete row.taskId; else row.unexpected = 'replay'; await reject(artifact, JSON.stringify(row), `${artifact}.${shape}-field`); }
  }
});

test('R3b correctly bound records reach real SQLite missing, foreign, wrong-phase, corrupt and contradictory checkpoint paths without new effects', async () => {
  const decisionReceived = async (directory: string) => { const current = await durable(directory); await assert.rejects(() => resumeLangGraph({ directory, threadId, record: current.record, correlationStore: current.store, task: current.task, checkpoints: async (name) => { if (name === 'before-resume-started') throw new Error('decision-received-only'); } }), /decision-received-only/); const next = await durable(directory); assert.equal(next.record.phase, 'decision-received'); return next; };
  const evidenceBytes = async (directory: string) => ({ ledger: await optionalText(effectPaths(directory).ledger), observation: await optionalText(effectPaths(directory).observation), receipt: await optionalText(join(directory, 'langgraph-receipt.json')) });
  const assertBlocked = async (directory: string, current: Awaited<ReturnType<typeof durable>>, label: string, expectedPhase: 'decision-received' | 'resumed', baseline?: Awaited<ReturnType<typeof evidenceBytes>>) => { const recordBytes = JSON.stringify(current.record); const taskBytes = await readFile(join(directory, 'oae-task.json'), 'utf8'); const before = baseline ?? await evidenceBytes(directory); let effects = 0; await assert.rejects(() => resumeLangGraph({ directory, threadId, record: current.record, correlationStore: current.store, task: current.task, onEffect: () => { effects += 1; } }), label); assert.equal(effects, 0, label); const after = await durable(directory); assert.equal(after.record.phase, expectedPhase, label); assert.equal(JSON.stringify(after.record), recordBytes, label); assert.equal(await readFile(join(directory, 'oae-task.json'), 'utf8'), taskBytes, label); assert.deepEqual(await evidenceBytes(directory), before, label); };

  { const directory = await pausedDirectory('approved'); const current = await decisionReceived(directory); await unlink(join(directory, 'langgraph-checkpoints.sqlite')); await assertBlocked(directory, current, 'missing correctly-bound thread checkpoint', 'decision-received'); }
  { const directory = await pausedDirectory('approved'); const current = await decisionReceived(directory); const foreignDirectory = await pausedDirectory('approved', false, donor); await writeFile(join(directory, 'langgraph-checkpoints.sqlite'), await readFile(join(foreignDirectory, 'langgraph-checkpoints.sqlite')), { mode: 0o600 }); await assertBlocked(directory, current, 'foreign swapped thread checkpoint', 'decision-received'); }
  { const directory = await pausedDirectory('approved'); const current = await decisionReceived(directory); const volatileStore = { save: async (_record: typeof current.record) => undefined }; const synthetic = await resumeLangGraph({ directory, threadId, record: current.record, correlationStore: volatileStore, task: current.task }); assert.equal(synthetic.phase, 'resumed'); const finalPhaseBaseline = await evidenceBytes(directory); assert.ok(finalPhaseBaseline.ledger); assert.ok(finalPhaseBaseline.observation); assert.ok(finalPhaseBaseline.receipt); await assertBlocked(directory, await durable(directory), 'final checkpoint where interrupted phase is required', 'decision-received', finalPhaseBaseline); }
  { const directory = await pausedDirectory('approved'); child('resume', directory, 'approved'); const current = await durable(directory); await writeFile(join(directory, 'langgraph-checkpoints.sqlite'), Buffer.from('not a sqlite database'), { mode: 0o600 }); await assertBlocked(directory, current, 'corrupt checkpoint bytes before receipt reconciliation', 'resumed'); }
  { const directory = await pausedDirectory('approved'); child('resume', directory, 'approved'); const current = await durable(directory); const opened = await openLangGraphSqlite(directory); try { const db = opened.saver.db as unknown as { prepare(sql: string): { get(...values: unknown[]): { checkpoint: Buffer; checkpoint_id: string } | undefined; run(...values: unknown[]): unknown } }; const row = db.prepare('SELECT checkpoint, checkpoint_id FROM checkpoints WHERE thread_id = ? ORDER BY checkpoint_id DESC LIMIT 1').get(threadId); assert.ok(row); const checkpoint = JSON.parse(Buffer.from(row.checkpoint).toString('utf8')) as { channel_values: Record<string, unknown> }; checkpoint.channel_values.decision = 'rejected'; db.prepare('UPDATE checkpoints SET checkpoint = ? WHERE thread_id = ? AND checkpoint_id = ?').run(Buffer.from(JSON.stringify(checkpoint)), threadId, row.checkpoint_id); } finally { await opened.close(); } await assertBlocked(directory, current, 'contradictory final checkpoint during receipt reconciliation', 'resumed'); }
});

test('R3 wrong, missing, or foreign thread binding fails before graph resume', async () => {
  const directory = await pausedDirectory('approved'); const current = await durable(directory); let effects = 0;
  await assert.rejects(() => resumeLangGraph({ directory, threadId: 'foreign-thread', record: current.record, correlationStore: current.store, task: current.task, onEffect: () => { effects += 1; } }), CorrelationSafetyError);
  await assert.rejects(() => resumeLangGraph({ directory, threadId, record: { ...current.record, approvalItemKey: null }, correlationStore: current.store, task: current.task, onEffect: () => { effects += 1; } }), CorrelationSafetyError); assert.equal(effects, 0); assert.equal((await current.store.load(correlationId)).phase, 'awaiting-input');
});

test('R3 hostile OAE terminal matrix rejects before the real LangGraph Command boundary', async () => {
  const mutations: Array<(task: OaeTask) => OaeTask> = [
    (task) => ({ ...task, id: 'foreign-task' }),
    (task) => ({ ...task, from: 'attacker@example.test', messages: task.messages.map((message, index) => index === 0 ? { ...message, from: 'attacker@example.test' } : message) }),
    (task) => ({ ...task, subject: `${task.subject} copied`, messages: task.messages.map((message) => ({ ...message, subject: `${message.subject} copied` })) }),
    (task) => ({ ...task, messages: task.messages.map((message) => message.state === 'completed' ? { ...message, from: 'attacker@example.test' } : message) }),
    (task) => ({ ...task, result: { decision: 'approved', extra: true }, messages: task.messages.map((message) => message.state === 'completed' ? { ...message, result: { decision: 'approved', extra: true } } : message) }),
  ];
  for (const mutate of mutations) { const directory = await pausedDirectory('approved'); const current = await durable(directory); let effects = 0; await assert.rejects(() => resumeLangGraph({ directory, threadId, record: current.record, correlationStore: current.store, task: mutate(current.task), onEffect: () => { effects += 1; } }), CorrelationSafetyError); assert.equal(effects, 0); assert.equal((await current.store.load(correlationId)).phase, 'awaiting-input'); }
});

test('R3 SQLite owner-only directory, database, sidecar and input boundaries reject unsafe state', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'r3-sqlite-safety-')); const opened = await openLangGraphSqlite(directory); await opened.close(); const database = join(directory, 'langgraph-checkpoints.sqlite'); await chmod(database, 0o644); await assert.rejects(() => openLangGraphSqlite(directory), CorrelationSafetyError); await chmod(database, 0o600);
  const victim = join(directory, 'victim'); await writeFile(victim, 'outside', { mode: 0o600 }); await unlink(database); await symlink(victim, database); await assert.rejects(() => openLangGraphSqlite(directory), CorrelationSafetyError); await unlink(database); const reset = await openLangGraphSqlite(directory); await reset.close(); await symlink(victim, `${database}-wal`); await assert.rejects(() => validateLangGraphSqlite(directory), CorrelationSafetyError);
  for (const unsafe of ['', 'Bearer credential-canary', 'sk-credentialcanary', 'safe\r\nunsafe']) assert.throws(() => safeLangGraphWorkflow(unsafe), CorrelationSafetyError);
});

test('R3 actual SQLite, sidecar, correlation, receipt and timeline artifacts exclude credential canaries', async () => {
  const directory = await pausedDirectory('approved'); child('resume', directory, 'approved'); const database = await readFile(join(directory, 'langgraph-checkpoints.sqlite'), 'utf8'); const correlation = await readFile(join(directory, 'correlation', `${correlationId}.json`), 'utf8'); const receipt = await readFile(join(directory, 'langgraph-receipt.json'), 'utf8'); const paths = effectPaths(directory); const ledger = await readFile(paths.ledger, 'utf8'); const observation = await readFile(paths.observation, 'utf8'); const record = (await durable(directory)).record; const timeline = JSON.stringify(sanitizedTimeline(record, [{ at: '2026-02-03T00:00:03.000Z', phase: 'resumed', code: 'resume-failed', authorization: 'Bearer credential-canary', rawBody: 'raw-workflow-r3' } as never])); assert.ok(database.includes('raw-workflow-r3')); for (const artifact of [correlation, receipt, ledger, observation, timeline]) { assert.ok(!artifact.includes('raw-workflow-r3')); assert.ok(!artifact.includes('credential-canary')); } for (const suffix of ['', '-wal', '-shm', '-journal']) { try { const sidecar = await readFile(join(directory, `langgraph-checkpoints.sqlite${suffix}`), 'utf8'); assert.ok(!sidecar.includes('credential-canary')); } catch { /* absent sidecars are valid and inventory is asserted separately */ } } assert.equal(langGraphApprovalKey(threadId), 'langgraph-thread:r3-thread-000000000001');
});
