import assert from 'node:assert/strict';
import test from 'node:test';
import { chmod, lstat, mkdir, mkdtemp, readFile, readdir, rename, symlink, unlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { OaeClient } from '../src/openagentemail.js';
import { createLocalFakeService, loadScenario, runScenario, sanitizeFailure, ScenarioFailure, writeScenarioArtifact } from '../src/scenario-runner.js';

const scenarios = join(process.cwd(), 'scenarios');
const environment = { OPENAGENTEMAIL_API_URL: 'http://oae-fixture.invalid', OAE_FIXTURE_REQUESTER_TOKEN: 'fixture-requester-scope', OAE_FIXTURE_RESPONDER_TOKEN: 'fixture-responder-scope' };
async function stateDirectory(label: string): Promise<string> { return mkdtemp(join(tmpdir(), `r4-${label}-`)); }
async function scenario(name: string) { return loadScenario(join(scenarios, `${name}.yaml`)); }

test('R4 caller-supplied YAML runs the complete submitted/input/working/completed path with scoped authors and exactly once handlers', async () => {
  const state = await stateDirectory('complete'); const input = await scenario('input-resume'); let pauses = 0; let resumes = 0;
  const result = await runScenario({ scenario: input, environment, stateDirectory: state, handlers: { pause: async () => { pauses += 1; }, resume: async () => { resumes += 1; } } });
  assert.deepEqual(result, { scenario: 'input-resume', correlationId: '11111111-1111-4111-8111-111111111111', taskId: 'scenario-task-1', state: 'completed', result: { decision: 'approved' }, frameworkPauses: 1, frameworkResumes: 1, events: [{ id: 'root-1', from: 'requester@example.test', state: 'submitted' }, { id: 'event-1', from: 'requester@example.test', state: 'input-required' }, { id: 'event-2', from: 'responder@example.test', state: 'working' }, { id: 'event-3', from: 'responder@example.test', state: 'completed' }] }); assert.equal(pauses, 1); assert.equal(resumes, 1);
  const record = JSON.parse(await readFile(join(state, 'correlation', '11111111-1111-4111-8111-111111111111.json'), 'utf8')) as Record<string, unknown>; assert.equal(record.phase, 'resumed'); assert.equal(record.taskId, 'scenario-task-1'); assert.equal((await lstat(join(state, 'correlation', '11111111-1111-4111-8111-111111111111.json'))).mode & 0o777, 0o600);
});

test('R4 restricted YAML parser accepts caller paths and all seven checked-in scenarios deterministically', async () => {
  const directory = await stateDirectory('caller'); const copied = join(directory, 'caller-supplied.yaml'); const source = await readFile(join(scenarios, 'input-resume.yaml'), 'utf8'); await writeFile(copied, source, { mode: 0o600 }); const input = await loadScenario(copied); assert.equal(input.name, 'input-resume');
  for (const name of ['input-resume', 'duplicate-delivery', 'timeout', 'stale-update', 'wrong-responder', 'swapped-participants', 'copied-marker']) assert.equal((await scenario(name)).name, name);
  const semanticDirectory = await stateDirectory('semantic'); for (const name of ['copied-marker', 'swapped-participants']) { const adverse = await scenario(name); await assert.rejects(() => runScenario({ scenario: adverse, environment, stateDirectory: semanticDirectory }), ScenarioFailure); await assert.rejects(() => lstat(join(semanticDirectory, 'correlation'))); }
});

test('R4 restricted YAML parser rejects syntax/schema/path confusion before token resolution or service mutation', async () => {
  const directory = await stateDirectory('parser'); const source = await readFile(join(scenarios, 'input-resume.yaml'), 'utf8'); const invalid: Record<string, string> = {
    anchor: `&anchor\n${source}`, alias: `${source}\nname: *anchor\n`, tag: `${source}\nname: !!str input-resume\n`, flow: source.replace('participants:', 'participants: {}\n#'), directive: `---\n${source}`, multidoc: `${source}\n---\n${source}`, duplicateKey: `${source}\nname: duplicate\n`, oddIndent: source.replace('  requester:', '   requester:'), inconsistentIndent: source.replace('      decision: approved', '        decision: approved'), scalarConfusion: source.replace('name: input-resume', 'name: true'), commentEdge: source.replace('name: input-resume', 'name: input-resume # comment'), colonEdge: source.replace('body: safe-workflow-r4', 'body: raw:colon'), unknown: `${source}\nunknown: no\n`, missing: source.replace('rootMessageId: root-1\n', ''), duplicateIdentity: source.replace('responder@example.test', 'requester@example.test'), duplicateSeed: source.replace('tasks:\n', 'tasks:\n  - id: scenario-task-1\n    from: requester\n    to: responder\n    subject: "Approval [scenario:11111111-1111-4111-8111-111111111111]"\n    body: safe-workflow-r4\n    rootMessageId: duplicate-root\n'), unsafe: source.replace('body: safe-workflow-r4', 'body: Bearer canary'),
  };
  for (const [name, content] of Object.entries(invalid)) { const path = join(directory, `${name}.yaml`); await writeFile(path, content, { mode: 0o600 }); await assert.rejects(() => loadScenario(path), ScenarioFailure, name); }
  const link = join(directory, 'linked.yaml'); await writeFile(copiedPath(directory), source, { mode: 0o600 }); await symlink(copiedPath(directory), link); await assert.rejects(() => loadScenario(link), ScenarioFailure); await assert.rejects(() => loadScenario(join(directory, 'not-yaml.txt')), ScenarioFailure); const missing: NodeJS.ProcessEnv = { ...environment }; missing.OAE_FIXTURE_RESPONDER_TOKEN = undefined; const valid = await scenario('input-resume'); await assert.rejects(() => runScenario({ scenario: valid, environment: missing, stateDirectory: join(directory, 'no-token-mutation') }), ScenarioFailure); await assert.rejects(() => lstat(join(directory, 'no-token-mutation', 'correlation')));
});

test('R4 fake authority separates requester/responder tokens and exposes no identity provisioning or admin bootstrap', async () => {
  const input = await scenario('input-resume'); const service = createLocalFakeService(input, environment); const identity = await service.fetch('http://oae-fixture.invalid/v1/identities', { method: 'POST', headers: { authorization: `Bearer ${environment.OAE_FIXTURE_REQUESTER_TOKEN}` } }); const unscoped = await service.fetch('http://oae-fixture.invalid/v1/tasks'); assert.equal(identity.status, 403); assert.equal(unscoped.status, 403); const body = await identity.text(); assert.ok(!body.includes(environment.OAE_FIXTURE_REQUESTER_TOKEN!)); assert.ok(!body.includes('admin'));
});

test('R4 ordinary polling observes non-terminal state while wait=true is terminal-only and returns its cap header', async () => {
  const input = await scenario('input-resume'); const service = createLocalFakeService(input, environment); const requester = new OaeClient({ baseUrl: environment.OPENAGENTEMAIL_API_URL!, token: environment.OAE_FIXTURE_REQUESTER_TOKEN!, fetch: service.fetch }); const responder = new OaeClient({ baseUrl: environment.OPENAGENTEMAIL_API_URL!, token: environment.OAE_FIXTURE_RESPONDER_TOKEN!, fetch: service.fetch });
  assert.equal((await requester.get('scenario-task-1')).state, 'submitted'); const waiting = await requester.waitForTerminal('scenario-task-1'); assert.equal(waiting.task.state, 'submitted'); assert.equal(waiting.timeoutSec, 1); await requester.inputRequired('scenario-task-1', 'approve-or-reject'); await (responder as unknown as { setState(id: string, state: 'working'): Promise<void> }).setState('scenario-task-1', 'working'); await responder.complete('scenario-task-1', { decision: 'approved' }); const terminal = await requester.waitForTerminal('scenario-task-1'); assert.equal(terminal.task.state, 'completed'); assert.equal(terminal.timeoutSec, undefined);
});

test('R4 duplicate delivery is idempotent; timeout measures a real bounded delay and stale/wrong-responder outcomes never add a second framework resume', async () => {
  const duplicate = await runScenario({ scenario: await scenario('duplicate-delivery'), environment, stateDirectory: await stateDirectory('duplicate') }); assert.equal(duplicate.frameworkPauses, 1); assert.equal(duplicate.frameworkResumes, 1); assert.equal(duplicate.events.length, 4);
  const rows: Array<{ name: string; code: 'timeout' | 'conflict'; pauses: number; resumes: number; }> = [{ name: 'timeout', code: 'timeout', pauses: 1, resumes: 0 }, { name: 'wrong-responder', code: 'conflict', pauses: 0, resumes: 0 }, { name: 'stale-update', code: 'conflict', pauses: 1, resumes: 1 }];
  for (const row of rows) { const input = await scenario(row.name); const state = await stateDirectory(row.name); let pauses = 0; let resumes = 0; await assert.rejects(() => runScenario({ scenario: input, environment, stateDirectory: state, handlers: { pause: async () => { pauses += 1; }, resume: async () => { resumes += 1; } } }), (error: unknown) => { assert.ok(error instanceof ScenarioFailure); assert.equal(error.failure.code, row.code); if (row.code === 'timeout') { assert.equal(error.failure.expectedState, 'completed'); assert.equal(error.failure.observedState, 'working'); assert.ok((error.failure.elapsedMs ?? -1) >= 4); assert.ok((error.failure.elapsedMs ?? Infinity) <= 60); assert.equal(error.failure.taskId, 'scenario-task-3'); assert.equal(error.failure.correlationId, '33333333-3333-4333-8333-333333333333'); } return true; }); assert.equal(pauses, row.pauses, row.name); assert.equal(resumes, row.resumes, row.name); }
});

test('R4a scheduler executes the before-deadline completion and fails after-deadline without a later transition', async () => {
  const before = structuredClone(await scenario('timeout')); before.name = 'before-deadline'; before.correlationId = '88888888-8888-4888-8888-888888888888'; before.tasks[0]!.id = 'scenario-task-before'; before.tasks[0]!.rootMessageId = 'root-before'; before.tasks[0]!.subject = `Approval [scenario:${before.correlationId}]`; for (const step of before.steps) step.task = 'scenario-task-before'; before.transitionDelayMs = 2; before.timeoutMs = 20;
  const result = await runScenario({ scenario: before, environment, stateDirectory: await stateDirectory('before-deadline') }); assert.equal(result.state, 'completed'); assert.equal(result.result?.decision, 'approved');
  let clock = 0; const sleeps: number[] = []; let resumes = 0; const expired = await scenario('timeout'); const expiredState = await stateDirectory('after-deadline'); await assert.rejects(() => runScenario({ scenario: expired, environment, stateDirectory: expiredState, timing: { now: () => clock, sleep: async (milliseconds) => { sleeps.push(milliseconds); clock += milliseconds; } }, handlers: { resume: async () => { resumes += 1; } } }), (error: unknown) => { assert.ok(error instanceof ScenarioFailure); assert.deepEqual(error.failure, { scenario: 'timeout', step: 2, code: 'timeout', expectedState: 'completed', observedState: 'working', taskId: 'scenario-task-3', correlationId: '33333333-3333-4333-8333-333333333333', elapsedMs: 5 }); return true; }); assert.deepEqual(sleeps, [5]); assert.equal(resumes, 0); const record = JSON.parse(await readFile(join(expiredState, 'correlation', '33333333-3333-4333-8333-333333333333.json'), 'utf8')) as Record<string, unknown>; assert.equal(record.phase, 'awaiting-input'); await Promise.resolve(); assert.equal(resumes, 0);
});

test('R4 sanitizes actual success/failure artifacts and keeps credentials/raw workflow out of exports', async () => {
  const directory = await stateDirectory('exports'); const success = await runScenario({ scenario: await scenario('input-resume'), environment, stateDirectory: join(directory, 'state') }); await writeScenarioArtifact(directory, 'success.json', success); const failure = sanitizeFailure(new ScenarioFailure({ scenario: 'timeout', step: 2, code: 'timeout', expectedState: 'completed', observedState: 'working', taskId: 'scenario-task-3', correlationId: '33333333-3333-4333-8333-333333333333', elapsedMs: 5 })); await writeScenarioArtifact(directory, 'failure.json', failure);
  for (const artifact of [await readFile(join(directory, 'success.json'), 'utf8'), await readFile(join(directory, 'failure.json'), 'utf8'), await readFile(join(directory, 'state', 'correlation', '11111111-1111-4111-8111-111111111111.json'), 'utf8')]) { assert.ok(!artifact.includes('fixture-requester-scope')); assert.ok(!artifact.includes('fixture-responder-scope')); assert.ok(!artifact.includes('safe-workflow-r4')); assert.ok(!artifact.includes('authorization')); } assert.equal((await lstat(join(directory, 'failure.json'))).mode & 0o777, 0o600);
});

test('R4a artifact store rejects unsafe targets and replacement races without corrupting prior bytes', async () => {
  const directory = await stateDirectory('artifact-store'); const first = { scenario: 'safe', step: 0, code: 'schema' as const }; const replacement = { scenario: 'safe', step: 1, code: 'timeout' as const };
  await writeScenarioArtifact(directory, 'failure.json', first); const target = join(directory, 'failure.json'); assert.equal(await readFile(target, 'utf8'), JSON.stringify(first)); assert.equal((await lstat(target)).mode & 0o777, 0o600); await writeScenarioArtifact(directory, 'failure.json', replacement); assert.equal(await readFile(target, 'utf8'), JSON.stringify(replacement));
  const victim = join(directory, 'victim.json'); await writeFile(victim, 'preserve-me', { mode: 0o600 }); const linked = join(directory, 'success.json'); await symlink(victim, linked); await assert.rejects(() => writeScenarioArtifact(directory, 'success.json', first)); assert.equal(await readFile(victim, 'utf8'), 'preserve-me');
  await chmod(target, 0o644); const unsafeBytes = await readFile(target, 'utf8'); await assert.rejects(() => writeScenarioArtifact(directory, 'failure.json', first)); assert.equal(await readFile(target, 'utf8'), unsafeBytes); await chmod(target, 0o600);
  await assert.rejects(() => writeScenarioArtifact(directory, '../failure.json' as never, first)); await assert.rejects(() => writeScenarioArtifact(directory, 'other.json' as never, first)); await unlink(linked); await mkdir(linked, { mode: 0o700 }); await assert.rejects(() => writeScenarioArtifact(directory, 'success.json', first));
  const race = await stateDirectory('artifact-race'); const raceTarget = join(race, 'failure.json'); await writeScenarioArtifact(race, 'failure.json', first); const attacker = join(race, 'attacker.json'); await writeFile(attacker, 'attacker-bytes', { mode: 0o600 }); await assert.rejects(() => writeScenarioArtifact(race, 'failure.json', replacement, { beforeRename: async () => { await rename(attacker, raceTarget); } })); assert.equal(await readFile(raceTarget, 'utf8'), 'attacker-bytes'); assert.deepEqual((await readdir(race)).filter((name) => name.startsWith('.failure.json.')), []);
});

test('R4 executable isolation guard recursively scans real production outputs and proves the scanner catches nested contamination', async () => {
  const root = resolve(process.cwd(), '../..'); const apiPackage = await readFile(join(root, 'packages/api/package.json'), 'utf8'); const dockerfile = await readFile(join(root, 'packages/api/Dockerfile'), 'utf8'); for (const text of [apiPackage, dockerfile]) { assert.ok(!text.includes('openagentemail-adapters-example')); assert.ok(!text.includes('@langchain/langgraph')); assert.ok(!text.includes('@openai/agents')); }
  for (const path of [join(root, 'packages/api/dist'), join(root, 'packages/api/build')]) await assertAdapterFree(await recursiveOutputFiles(path));
  const proof = await stateDirectory('recursive-output'); const nested = join(proof, 'dist', 'nested', 'asset.js'); await mkdir(resolve(nested, '..'), { recursive: true, mode: 0o700 }); await writeFile(nested, 'clean production output', { mode: 0o600 }); await assertAdapterFree(await recursiveOutputFiles(join(proof, 'dist'))); await writeFile(nested, 'import "@openai/agents"', { mode: 0o600 }); await assert.rejects(async () => assertAdapterFree(await recursiveOutputFiles(join(proof, 'dist'))));
});

function copiedPath(directory: string): string { return join(directory, 'anchor-source.yaml'); }
async function recursiveOutputFiles(directory: string): Promise<string[]> { let root; try { root = await lstat(directory); } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return []; throw error; } if (!root.isDirectory() || root.isSymbolicLink()) throw new Error(`unsafe production output directory: ${directory}`); const files: string[] = []; for (const entry of await readdir(directory, { withFileTypes: true })) { const path = join(directory, entry.name); const metadata = await lstat(path); if (metadata.isSymbolicLink()) throw new Error(`symlinked production output: ${path}`); if (metadata.isDirectory()) files.push(...await recursiveOutputFiles(path)); else if (metadata.isFile()) files.push(path); else throw new Error(`unsupported production output entry: ${path}`); } return files; }
async function assertAdapterFree(paths: string[]): Promise<void> { for (const path of paths) { const contents = await readFile(path, 'utf8'); assert.ok(!path.includes('openagentemail-adapters-example')); assert.ok(!contents.includes('openagentemail-adapters-example')); assert.ok(!contents.includes('@langchain/langgraph')); assert.ok(!contents.includes('@openai/agents')); } }
