import {
  setTaskNowForTests,
  setTaskListAllForTests,
  setTaskGetForTests,
  setTaskSendMailForTests,
  clearQueuedEventsForTests,
  scanDurableTasksForTests,
  takeApprovalWatcherParseCallsForTests,
  takeLeaseOverlayReplayExpiredCountForTests,
  takeClaimWindowConflictDegradedCountForTests,
  takeClaimFenceExpiredCountForTests,
  getTaskSnapshot,
  LEASE_OVERLAY_MAX_LIFETIME_MS,
  CLAIM_FENCE_MAX_MS,
  LEASE_OVERLAY_REPLAY_EXPIRED_SEEN_CAP,
  LEASE_OVERLAY_REPLAY_EXPIRED_WARN_INTERVAL_MS,
  queueLeaseOverlayForTests,
  queuedLeaseOverlayCountForTests,
} from '../../src/lib/tasks-internal.ts';

export {
  setTaskNowForTests,
  setTaskListAllForTests,
  setTaskGetForTests,
  setTaskSendMailForTests,
  clearQueuedEventsForTests,
  scanDurableTasksForTests,
  takeApprovalWatcherParseCallsForTests,
  takeLeaseOverlayReplayExpiredCountForTests,
  takeClaimWindowConflictDegradedCountForTests,
  takeClaimFenceExpiredCountForTests,
  getTaskSnapshot,
  LEASE_OVERLAY_MAX_LIFETIME_MS,
  CLAIM_FENCE_MAX_MS,
  LEASE_OVERLAY_REPLAY_EXPIRED_SEEN_CAP,
  LEASE_OVERLAY_REPLAY_EXPIRED_WARN_INTERVAL_MS,
  queueLeaseOverlayForTests,
  queuedLeaseOverlayCountForTests,
};
