import {
  setTaskNowForTests,
  setTaskListAllForTests,
  setTaskGetForTests,
  setTaskSendMailForTests,
  clearQueuedEventsForTests,
  scanDurableTasksForTests,
  getQueuedEventsForTests,
  seedQueuedEventForTests,
  getStaleLeaseOverlayAlertCountForTests,
  getPendingExpiryAuditCountForTests,
  getExpiryAuditLingerAlertCountForTests,
  rebuildExpiryAuditRetryQueueFromMessages,
  retryPendingExpiryAuditsOnce,
  LEASE_OVERLAY_MAX_LIFETIME_MS,
  EXPIRY_AUDIT_MAX_ATTEMPTS,
} from '../../src/lib/tasks-internal.ts';

export {
  setTaskNowForTests,
  setTaskListAllForTests,
  setTaskGetForTests,
  setTaskSendMailForTests,
  clearQueuedEventsForTests,
  scanDurableTasksForTests,
  getQueuedEventsForTests,
  seedQueuedEventForTests,
  getStaleLeaseOverlayAlertCountForTests,
  getPendingExpiryAuditCountForTests,
  getExpiryAuditLingerAlertCountForTests,
  rebuildExpiryAuditRetryQueueFromMessages,
  retryPendingExpiryAuditsOnce,
  LEASE_OVERLAY_MAX_LIFETIME_MS,
  EXPIRY_AUDIT_MAX_ATTEMPTS,
};
